# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Share2Us.CLI
PackageVersion: "20260904061335"
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
Commands:
  - s2u
  - share2us
NestedInstallerFiles:
  - RelativeFilePath: share2us.exe
    PortableCommandAlias: s2u
  - RelativeFilePath: share2us.exe
    PortableCommandAlias: share2us
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/share2us/cli/releases/download/v20260904061335/share2us_windows_amd64.zip
    InstallerSha256: 97F9D7C68A326C4EE3656B881829BDAD7CE2A1192285D8CB32528AFE9B3EC384
  - Architecture: arm64
    InstallerUrl: https://github.com/share2us/cli/releases/download/v20260904061335/share2us_windows_arm64.zip
    InstallerSha256: 45DE4CD5C8E2B5331C901EDED3F8EB8E45C78567C587B27D73CBDD6E9B6AA648
ManifestType: installer
ManifestVersion: 1.6.0
