# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json
PackageIdentifier: Share2Us.CLI
PackageVersion: "20260904061335"
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
