// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 Hassan Khurram

package daemon

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Gemini guardrail enforcement (ADR-036). --approval-mode alone is not a gate:
// it decides whether edits are auto-approved, not what may run, and it knows
// nothing about "never push". Gemini's real enforcement is its policy engine —
// TOML rules with decision = "deny", which are not merely refused but removed
// from the model's tool list entirely, so the prompt cannot argue its way past
// them.
//
// The compiled .s2u.rules are written to a per-run policy file and passed with
// --admin-policy, the highest tier (above user and workspace policies), so a
// project's own ~/.gemini/policies cannot loosen what the machine owner set.

// geminiAdminPolicyDir is the standard system policy location on Linux. If it
// holds any .toml, Gemini IGNORES supplemental --admin-policy paths entirely
// (its anti-override guard), which would silently drop our guardrails.
const geminiAdminPolicyDir = "/etc/gemini-cli/policies"

// geminiDenyMessage is returned to the model and the user when a rule blocks a
// call, so the refusal is attributable rather than mysterious.
const geminiDenyMessage = "blocked by the .s2u.rules on this machine"

// geminiPolicyPriority is high within the admin tier; the tier already outranks
// user/workspace rules, this just orders us above any other admin file.
const geminiPolicyPriority = 900

// writeGeminiPolicy renders the policy to a TOML file in its own directory and
// returns that directory (to pass to --admin-policy) plus a cleanup func.
func writeGeminiPolicy(p Policy) (dir string, cleanup func(), err error) {
	toml := geminiPolicyTOML(p)
	if toml == "" {
		return "", func() {}, nil
	}
	dir, err = os.MkdirTemp("", "s2u-gemini-policy-")
	if err != nil {
		return "", func() {}, err
	}
	cleanup = func() { os.RemoveAll(dir) }
	if err := os.WriteFile(filepath.Join(dir, "s2u-rules.toml"), []byte(toml), 0o600); err != nil {
		cleanup()
		return "", func() {}, err
	}
	return dir, cleanup, nil
}

// geminiPolicyTOML compiles the deny patterns into policy-engine rules. Shell
// denies become commandPrefix rules; file denies become argsPattern rules over
// the write tools. Advisory rules cannot be compiled and stay in the prompt.
func geminiPolicyTOML(p Policy) string {
	var b strings.Builder
	b.WriteString("# Generated by Share2Us for one injected run (ADR-036). Do not edit.\n")
	b.WriteString("# Source: .s2u.rules on the target machine.\n")
	n := 0
	for _, pattern := range p.DisallowedTools {
		tool, inner, ok := splitDenyPattern(pattern)
		if !ok {
			continue
		}
		switch tool {
		case "Bash":
			fmt.Fprintf(&b, "\n[[rule]]\ntoolName = \"run_shell_command\"\ncommandPrefix = %s\ndecision = \"deny\"\npriority = %d\ndenyMessage = %s\n",
				tomlLiteral(inner), geminiPolicyPriority, tomlLiteral(geminiDenyMessage))
			n++
		case "Edit", "Write":
			fmt.Fprintf(&b, "\n[[rule]]\ntoolName = [\"write_file\", \"replace\"]\nargsPattern = %s\ndecision = \"deny\"\npriority = %d\ndenyMessage = %s\n",
				tomlLiteral(globToArgsPattern(inner)), geminiPolicyPriority, tomlLiteral(geminiDenyMessage))
			n++
		}
	}
	if n == 0 {
		return ""
	}
	return b.String()
}

// splitDenyPattern splits "Bash(git push:*)" into ("Bash", "git push", true).
func splitDenyPattern(pattern string) (tool, inner string, ok bool) {
	open := strings.Index(pattern, "(")
	if open < 0 || !strings.HasSuffix(pattern, ")") {
		return "", "", false
	}
	inner = strings.TrimSuffix(pattern[open+1:len(pattern)-1], ":*")
	if inner == "" {
		return "", "", false
	}
	return pattern[:open], inner, true
}

// globToArgsPattern turns a path glob into a regex tested against the tool's
// JSON arguments. Conservative: matches the glob's literal tail anywhere in the
// args, which over-blocks rather than under-blocks.
func globToArgsPattern(glob string) string {
	tail := glob
	if i := strings.LastIndex(tail, "*"); i >= 0 {
		tail = tail[i+1:]
	}
	tail = strings.TrimPrefix(tail, "/")
	if tail == "" {
		tail = glob
	}
	return regexpQuoteMeta(tail)
}

// regexpQuoteMeta escapes regex metacharacters (regexp.QuoteMeta, kept local to
// document that the output is embedded in TOML, not compiled here).
func regexpQuoteMeta(s string) string {
	const special = `\.+*?()|[]{}^$`
	var b strings.Builder
	for _, r := range s {
		if strings.ContainsRune(special, r) {
			b.WriteByte('\\')
		}
		b.WriteRune(r)
	}
	return b.String()
}

// tomlLiteral renders a value as a TOML literal string (single quotes, no escape
// processing) — the right form for regexes and command prefixes, and it avoids
// Go's %q emitting \xNN escapes that TOML does not accept. A literal string
// cannot contain a single quote, so any are dropped.
func tomlLiteral(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "") + "'"
}

// geminiSystemPolicyPresent reports whether the standard admin policy directory
// holds any .toml. When it does, Gemini ignores --admin-policy paths, so our
// guardrails would not apply and the caller must refuse to inject.
func geminiSystemPolicyPresent() bool {
	entries, err := os.ReadDir(geminiAdminPolicyDir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".toml") {
			return true
		}
	}
	return false
}
